### ISSUE TITLE
No stub was found which matches the arguments of this method call

### ISSUE THREAD

**Issue by cuongvue** [dart-lang/mockito#402] opened 2021-05-02 04:24 UTC
I have a Cat model with a method that returns a non-null String as:
```
class Cat {
  String sound() => "Meow";
}
```
Then I try to run the test like:
```
@GenerateMocks([Cat])
main() {
  test("verify", () {
    var cat = MockCat();
    cat.sound();
    verify(cat.sound());
  });
}
```
But then I have an error:
```
package:mockito/src/mock.dart 190:7   Mock._noSuchMethod
package:mockito/src/mock.dart 184:45  Mock.noSuchMethod
test/mock_test.mocks.dart 25:14       MockCat.sound
test/mock_test.dart 12:9              main.<fn>

MissingStubError: 'sound'
No stub was found which matches the arguments of this method call:
sound()

Add a stub for this method using Mockito's 'when' API, or generate the mock for MockCat with 'returnNullOnMissingStub: true'.
```

How to fix the error please. I'm using `mockito: ^5.0.7`, below is my `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by srawlins** [comment] 2021-05-03 03:36
Since no stub was created with the `when` API, the call, `cat.sound();` throws. The last line which you pasted gives two possible fixes.

**Comment by cuongvue** [comment] 2021-05-03 06:04
@srawlins I'm not sure how to do that. What is a stub and how to create it? could you please share me some code?

**Comment by srawlins** [comment] 2021-05-03 13:55
The "stub" is the mock method response. Something like `when(cat.sound()).thenReturn('a');` will create a stub for the method, causing it to return `'a'`.

The second option is to use the [`returnNullOnMissingStub`](https://pub.dev/documentation/mockito/latest/annotations/MockSpec/returnNullOnMissingStub.html) parameter of MockSpec: `@GenerateMocks([], customMocks: [MockSpec(Cat, returnNullOnMissingStub: true)])`

**Comment by cuongvue** [comment] 2021-05-04 14:02
@srawlins I try `@GenerateMocks([], customMocks: [MockSpec(Cat, returnNullOnMissingStub: true)])` but get the compile error as `Too many positional arguments: 0 expected, but 1 found.`. Trying `@GenerateMocks([], customMocks: [MockSpec(as: Cat, returnNullOnMissingStub: true)])` I get `In a const constructor, a value of type 'Type' can't be assigned to the field 'mockName', which has type 'Symbol?'.`

**Comment by srawlins** [comment] 2021-05-04 14:44
Sorry, `MockSpec` does not have any positional parameters; I made a typo. See https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#custom-generated-mocks for the syntax.

**Comment by cuongvue** [comment] 2021-05-05 14:38
My build_runner version is `^1.11.0`. I try to change my test file as:
```
@GenerateMocks([], customMocks: [
  MockSpec<Cat>(
    as: #BaseMockCat,
    returnNullOnMissingStub: true,
  )
])
main() {
  test("verify", () {
    var cat = MockCat();
    cat.sound();
    verify(cat.sound());
  });
}
```
Then I call `dart run build_runner build ` and get a error like:
```
Precompiling executable... (8.7s)
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:49: Warning: Operand of null-aware operation '??' has type 'bool' which excludes null.
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                                ^
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder

For solutions, see https://dart.dev/go/unsound-null-safety
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:37: Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.1.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                    ^
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:49: Warning: Operand of null-aware operation '??' has type 'bool' which excludes null.
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                                ^
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder

For solutions, see https://dart.dev/go/unsound-null-safety
../../.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:37: Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.1.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
```
If I change build_runner to `^2.0.2` and call `dart run build_runner build `, I will get error `Could not find a file named "pubspec.yaml" in "/Users/nguyencuong/.pub-cache/hosted/pub.dartlang.org/build_runner-2.0.2".
` @srawlins

**Comment by srawlins** [comment] 2021-05-05 15:07
Sorry I can't help with those build_runner issues.

**Comment by natebosch** [comment] 2021-05-06 20:28
Closing as a duplicate of https://github.com/dart-lang/build/issues/3046 - please follow there for updates.

There seems to be a bug in `dart run` where it is using the wrong language version. Upgrading to `build_runner` version `2.0.0` may be a workaround.

**Closed by natebosch** 2021-05-06 20:28 UTC

**Comment by cuongvue** [comment] 2021-05-07 13:57
using `build_runner 2.0.1` can generate the .mocks.dart file but running my test results an error like:
```
test/mock_test.mocks.dart 22:11  MockCat.sound
test/mock_test.dart 17:9         main.<fn>

type 'Null' is not a subtype of type 'String' in type cast
```

**Comment by srawlins** [comment] 2021-05-07 15:47
Sorry, @cuongvue the `returnNullOnMissingStub` route will not work for your case, because `sound` returns a non-nullable String; `null` is not a valid return value.

**Comment by cuongvue** [comment] 2021-05-08 04:51
@srawlins so how can I test the `String sound() => "Meow";` function please?

**Comment by srawlins** [comment] 2021-05-08 04:54
I'm not sure I understand your question. Mockito will not help you test a class's methods. It replaces the implementation of each of a method's classes with its own, making it impossible to test the class itself. You cannot get the original "Meow" out of a Mock implementation of Cat.

**Comment by cuongvue** [comment] 2021-05-08 04:59
```
@GenerateMocks([Cat])
main() {
  test("verify", () {
    var cat = MockCat();
    cat.sound();
    verify(cat.sound());
  });
}
```
my question is how can I run `verify(cat.sound());` in test function without an error? @srawlins

**Comment by srawlins** [comment] 2021-05-08 19:39
You'll have to stub the method first. Something like `when(cat.sound()).thenReturn('a');`, as I [mentioned above](https://github.com/dart-lang/mockito/issues/402#issuecomment-831275351).

**Comment by nguyennhutuanhung** [comment] 2021-12-10 08:55
I tried this and it worked
```
@GenerateMocks([], customMocks: [MockSpec<Cat>(returnNullOnMissingStub: true)])
void main() {
  // Create mock object.
  test('test',(){
    var cat = MockCat();
    try{
      cat.eatFood('bc');
    }catch(e){
    };
    verify(cat.eatFood('bc')).called(1);
  }
  );
}

**Comment by Douoo** [comment] 2022-12-27 07:04
can anyone tell me how to implement OnMissingStub? onMissingStub parameter - the returnNullOnMissingStub is deprecated

**Comment by srawlins** [comment] 2022-12-27 16:42
@Douoo you're best bet is to ask on a user forum like StackOverflow, or open a new issue if you think we are missing documentation.

**Comment by jbankz** [comment] 2023-01-21 00:33
> 

`@GenerateNiceMocks(
    [MockSpec<AuthRepositoryImpl>(onMissingStub: OnMissingStub.returnDefault)])`
