### ISSUE TITLE
throwOnMissingStub doesn't actually throw

### ISSUE THREAD

**Issue by JZ-at-TP** [dart-lang/mockito#187] opened 2019-01-24 19:35 UTC
I've setup a mock to use `throwOnMissingStub` but it just prints out to the console, it doesn't actually throw. This means the tests still pass when they shouldn't. Maybe create a `throwOnMissingStub` and rename the current implementation to `printOnMissingStub`.

**Comment by srawlins** [comment] 2019-02-08 21:17
Sorry for the delayed response. throwOnMissingSub calls[Object.noSuchMethod](_noSuchMethod), which should throw.

Can you give a full example?

**Comment by JZ-at-TP** [comment] 2019-02-13 18:00
```class MockHttpClient extends Mock implements http.Client {
  MockHttpClient() {
    throwOnMissingStub(this);
  }
}```

Running with this, we get no throws when http calls are made without a `when`.

**Comment by srawlins** [comment] 2019-02-14 17:59
It works for me.

*pubspec.yaml:*

```yaml
name: mockito_example

dependencies:
  mockito: 'any'
dev_dependencies:
  build_runner: 'any'
  build_test: 'any'
  build_web_compilers: 'any'
```

*web/index.html:*

```html
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello World</title>
  <link rel="icon" type="image/png" href="favicon.png">
  <script defer src="main.dart.js"></script>
  </head>
  <body>
  </body>
</html>
```

*web/main.dart:*

```dart
import 'package:mockito/mockito.dart';
import 'dart:html' as html;

void main() {
  var client = MockClient();
  client.postMessage(1);
}

class MockClient extends Mock implements html.Client {
  MockClient() {
    throwOnMissingStub(this);
  }
}
```

`$ webdev serve`

In the browser console:

```
Uncaught core.NoSuchMethodError.withInvocation {requireMap: {…}, requireModules: Array(1), requireType: "define", Symbol(_receiver): c…e.O…t.new, Symbol(_memberName): _…r.P…l.new, …}
```

**Comment by natebosch** [comment] 2019-05-02 00:12
Closing since this doesn't seem actionable. If you can post a reproduction case we can explore this further.

**Closed by natebosch** 2019-05-02 00:12 UTC
Labels: State: needs info
