### ISSUE TITLE
when is not be matched when calling a callable class

### ISSUE THREAD

**Issue by AAkira** [dart-lang/mockito#287] opened 2020-10-12 07:56 UTC
A `when` definition is not matched if you call a mock value of an argument in `when` functions.
Therefore, `Hoge.call()` is null.

This example code doesn't work.
Do you have any idea?

* Dart code

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

class Foo {
  Future<int> call(Arguments arguments) {
    return Future<int>.value(654321);
  }
}

class MockFoo extends Mock implements Foo {}

class Bar {
  int call() {
    return 123456;
  }
}

class MockBar extends Mock implements Bar {}

class Hoge {
  const Hoge({
    this.foo,
    this.bar,
  });

  final Foo foo;
  final Bar bar;

  Future<int> call() {
    return foo(Arguments(first: 8888, second: bar()));
  }
}

class Arguments {
  const Arguments({
    this.first,
    this.second,
  });

  final int first;
  final int second;
}

void main() {
  test('test', () async {
    final Foo foo = MockFoo();
    final Bar bar = MockBar();
    final Hoge hoge = Hoge(foo: foo, bar: bar);

    when(bar()).thenReturn(1000);
    when(foo(const Arguments(first: 8888, second: 1000)))
        .thenAnswer((_) async => 10);

    final result = await hoge();

    expect(result, 10);
  });
}
```

* Result

```
Expected: <10>
Actual: <null>
```

Mockito version: 4.1.2
Dart version: 2.10.0

**Comment by srawlins** [comment] 2020-10-12 15:24
Yeah in general I doubt Mockito supports the callable class interface ideas. What if you change `when(bar()).thenReturn(1000);` to `when(bar.call()).thenReturn(1000);?

**Comment by AAkira** [comment] 2020-10-13 03:30
It still didn't work. 😢

I implement the hashCode in Argument class.
It works.

Do you have a plan to support a callable class in Mockito?

```
@immutable
class Arguments {
  const Arguments({
    this.first,
    this.second,
  });

  final int first;
  final int second;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Arguments &&
          runtimeType == other.runtimeType &&
          first == other.first &&
          second == other.second;

  @override
  int get hashCode => first.hashCode ^ second.hashCode;
}
```

**Comment by srawlins** [comment] 2021-05-26 00:21
Duplicate of https://github.com/dart-lang/mockito/issues/277

**Closed by srawlins** 2021-05-26 00:21 UTC
