### ISSUE TITLE
Cannot generate mock of class which mixes in DiagnosticableTreeMixin

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/mockito#400] opened 2021-04-29 12:30 UTC
Since the recommended way is to code generate mocks, is there a way to use code generation with the fix mentioned here?
https://github.com/dart-lang/mockito/issues/233

**Comment by matejthetree** [comment] 2021-04-29 12:36
to test this, try to generate mocks for this class

**class TestFor with DiagnosticableTreeMixin {}
**

**Comment by matejthetree** [comment] 2021-04-29 12:54
https://github.com/dart-lang/mockito/issues/397 A question for code generation was asked here as well, but the answer pointed to manual implementation.

**Comment by matejthetree** [comment] 2021-05-03 07:16
thinking about this, if we could override the mocked class somehow to make this work, or maybe use it as a mixin.

what do you guys think?

**Comment by srawlins** [comment] 2021-05-03 14:17
@matejthetree This issue's description is a mystery to me. I'm not sure what problem or question you have. I'm not sure what "diagnostics problem" means.

In reference to the issues about overriding toString with additional parameters, I have an unrelated proposal to allow one to mix in a mixin: https://github.com/dart-lang/mockito/issues/342. Not sure if it would solve this issue...

**Comment by matejthetree** [comment] 2021-05-06 10:43
@srawlins thanks for the proposal. It might work by creating the mixin that overrides to String.

The issue can be easily reproduced by trying to generate mock for 
`class Test with DiagnosticableTreeMixin {}`

Looking forward to your updates

**Comment by srawlins** [comment] 2021-06-01 15:15
Sorry for the delay @matejthetree. I do't know what DiagnosticableTreeMixin is. Is this a class you wrote? I'll need a self-contained minimal reproduction in order to debug.

**Comment by matejthetree** [comment] 2021-06-02 11:59
It is a flutter debug class that is implemented if you want your widget to have custom debug data in the flutter inspection (dev tools). It is used a lot when writing frameworks, to provide details about the state from the inspector itself.

I will make a simple app that you can clone.

**Comment by matejthetree** [comment] 2021-06-02 12:46
here it is.

Write this test with the latest version of mockito.

```dart
import 'package:flutter/foundation.dart';
import 'package:mockito/annotations.dart';

@GenerateMocks([Test])
void main() {}

class Test with DiagnosticableTreeMixin {}
```

The file created will have this error:

```
'Object.toString' ('String Function()') isn't a valid concrete implementation of 'DiagnosticsNode.toString' ('String Function({DiagnosticLevel minLevel, TextTreeConfiguration? parentConfiguration})').
```

I have to go and create manual mocks for huge classes, and this makes it a bit hard to test :)

it would be nice If I could define a mixin that would handle this problematic function that I have in all my business logic.

**Comment by srawlins** [comment] 2021-06-02 16:05
Ah yes. Similar to https://github.com/dart-lang/mockito/issues/371, but that is for Fakes. This is for Mocks.

**Comment by srawlins** [comment] 2021-06-02 21:06
I suspect this is fixed in 5.0.9, but I'm not certain. I cannot reproduce this at HEAD.

**Comment by matejthetree** [comment] 2021-06-03 10:25
great. Let me try with latest git release

**Comment by matejthetree** [comment] 2021-06-03 10:34
This is in fact the fake error.

Here is the output I get from latest git mockito.

```dart
class _FakeDiagnosticsNode extends _i1.Fake implements _i2.DiagnosticsNode {}

/// A class which mocks [Test].
///
/// See the documentation for Mockito's code generation for more information.
class MockTest extends _i1.Mock implements _i3.Test {
  MockTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
  @override
  String toStringShallow(
          {String? joiner = r', ',
          _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.debug}) =>
      (super.noSuchMethod(
          Invocation.method(
              #toStringShallow, [], {#joiner: joiner, #minLevel: minLevel}),
          returnValue: '') as String);
  @override
  String toStringDeep(
          {String? prefixLineOne = r'',
          String? prefixOtherLines,
          _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.debug}) =>
      (super.noSuchMethod(
          Invocation.method(#toStringDeep, [], {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel
          }),
          returnValue: '') as String);
  @override
  String toStringShort() => (super
          .noSuchMethod(Invocation.method(#toStringShort, []), returnValue: '')
      as String);
  @override
  _i2.DiagnosticsNode toDiagnosticsNode(
          {String? name, _i2.DiagnosticsTreeStyle? style}) =>
      (super.noSuchMethod(
          Invocation.method(
              #toDiagnosticsNode, [], {#name: name, #style: style}),
          returnValue: _FakeDiagnosticsNode()) as _i2.DiagnosticsNode);
  @override
  List<_i2.DiagnosticsNode> debugDescribeChildren() =>
      (super.noSuchMethod(Invocation.method(#debugDescribeChildren, []),
          returnValue: <_i2.DiagnosticsNode>[]) as List<_i2.DiagnosticsNode>);
  @override
  void debugFillProperties(_i2.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(Invocation.method(#debugFillProperties, [properties]),
          returnValueForMissingStub: null);
}
```

End the error is indeed on
```
class _FakeDiagnosticsNode extends _i1.Fake implements _i2.DiagnosticsNode {}
```

**Comment by matejthetree** [comment] 2021-06-03 10:43
I tried to do it with new API but with no luck

```
@GenerateMocks([
  Test
], customMocks: [
  MockSpec<Test>(as: #TestCustom, fallbackGenerators: {#toString: toString})
])
String toString(
    {TextTreeConfiguration? parentConfiguration,
    DiagnosticLevel? minLevel = DiagnosticLevel.info}) {
  return '';
}
```

**Comment by srawlins** [comment] 2021-06-03 18:21
OK this is a duplicate of #371 then.

**Closed by srawlins** 2021-06-03 18:21 UTC
