### ISSUE TITLE
Cant create MockClass of a class that extends another

### ISSUE THREAD

**Issue by RickZzDev** [dart-lang/mockito#296] opened 2020-11-16 00:26 UTC
Hello, i'm trying to create a mock class that implements an abastract class, and this abstract class extends one state, that's the code.

Abstract class
abstract class WidgetTesteViewModel extends State<WidgetTeste> {}

Mock
class WidgetTestSpy extends Mock implements WidgetTesteViewModel{}

Error:
'Mock.toString' ('String Function()') isn't a valid override of 'Diagnosticable.toString' ('String Function({DiagnosticLevel minLevel})')

**Comment by srawlins** [comment] 2020-11-16 02:03
Thanks for opening an issue. This has been discussed at https://github.com/dart-lang/mockito/issues/233. See [the solution](https://github.com/dart-lang/mockito/issues/233#issuecomment-607533095).

**Comment by srawlins** [comment] 2020-11-16 02:03
Duplicate of #233

**Closed by srawlins** 2020-11-16 02:03 UTC
