### ISSUE TITLE
@GenerateMocks does not generate for void function without parameter

### ISSUE THREAD

**Issue by EhiltonKazuo** [dart-lang/mockito#367] opened 2021-03-16 19:53 UTC
I'm new in mockito and null safety operators, but i followed the NULL_SAFETY_README. This is the annotation that im using:
`@GenerateMocks([],
    customMocks: [MockSpec<LoginPresenter>(as: #LoginPresenterSpy)])`

This is the sample of LoginPresenter:
```
abstract class LoginPresenter {
  Stream<String> get emailErrorStream;
  Stream<String> get passwordErrorStream;
  Stream<String> get mainErrorStream;
  Stream<bool> get isFormValidStream;
  Stream<bool> get isLoadingStream;

  void validateEmail(String email);
  void validatePassword(String password);
  void auth();
  void dispose();
}
```
And this is the generate code build_runner:

```
class LoginPresenterSpy extends _i1.Mock implements _i2.LoginPresenter {
  LoginPresenterSpy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> get emailErrorStream =>
      (super.noSuchMethod(Invocation.getter(#emailErrorStream),
          returnValue: Stream<String>.empty()) as _i3.Stream<String>);
  @override
  _i3.Stream<String> get passwordErrorStream =>
      (super.noSuchMethod(Invocation.getter(#passwordErrorStream),
          returnValue: Stream<String>.empty()) as _i3.Stream<String>);
  @override
  _i3.Stream<String> get mainErrorStream =>
      (super.noSuchMethod(Invocation.getter(#mainErrorStream),
          returnValue: Stream<String>.empty()) as _i3.Stream<String>);
  @override
  _i3.Stream<bool> get isFormValidStream =>
      (super.noSuchMethod(Invocation.getter(#isFormValidStream),
          returnValue: Stream<bool>.empty()) as _i3.Stream<bool>);
  @override
  _i3.Stream<bool> get isLoadingStream =>
      (super.noSuchMethod(Invocation.getter(#isLoadingStream),
          returnValue: Stream<bool>.empty()) as _i3.Stream<bool>);
  @override
  void validateEmail(String? email) =>
      super.noSuchMethod(Invocation.method(#validateEmail, [email]),
          returnValueForMissingStub: null);
  @override
  void validatePassword(String? password) =>
      super.noSuchMethod(Invocation.method(#validatePassword, [password]),
          returnValueForMissingStub: null);
}
```

But doesn't exist the auth and dispose functions. Am i doing wrong?

**Comment by srawlins** [comment] 2021-03-16 21:03
Nope; you are not doing anything wrong. `Mock.noSuchMethod` will handle those methods.

**Comment by mateusdeap** [comment] 2021-04-01 12:57
I'm not sure I understand. I'm coming across a problem where I have methods similar to @EhiltonKazuo's which return voi and have no parameters, and the generated mock class does not override them. Thus, when I call `flutter test` I get:
```
MissingStubError: 'start'
  No stub was found which matches the arguments of this method call:
  start()
  
  Add a stub for this method using Mockito's 'when' API, or generate the mock for MockTomato with 'returnNullOnMissingStub: true'.
  package:mockito/src/mock.dart 190:7                         Mock._noSuchMethod
  package:mockito/src/mock.dart 184:45                        Mock.noSuchMethod
  package:focus_index/domain/entities/tomato.dart 2:8         MockTomato.start
  package:focus_index/domain/usecases/start_timer.dart 11:18  StartTimer.execute
  test/usecases/start_timer_test.dart 29:13                   main.<fn>.<fn>.<fn>
```

**Comment by mateusdeap** [comment] 2021-04-05 18:52
So I got it to pass by modifying the annotation as suggested in the NULL_SAFETY_README:
`@GenerateMocks([], customMocks: [MockSpec<Tomato>(returnNullOnMissingStub: true)])`

However, I don't know if this is what I should be doing since it is not the case that my method returns null. But I don't really know if a void return type is equivalent to returning null, so...

**Comment by EhiltonKazuo** [comment] 2021-04-06 17:51
I think you only use this, if your code is legacy. I will wait the new update to solve this.

**Comment by natebosch** [comment] 2021-04-07 00:26
> However, I don't know if this is what I should be doing since it is not the case that my method returns null. But I don't really know if a void return type is equivalent to returning null, so...

This is the behavior of mockito before the null safety migration. `void` is a type which any value can flow into. You can return any value at all through a `void` return type, the value `null` happens to be the most common one. If you don't have an explicit `return` statement, a `null` will still be returned.

The `returnNullOnMissingStub` configuration could have been named something like `allowMissingStubs` and we chose the default of `false` because we think it's a better practice that behavior is explicitly stubbed instead of implicitly allowing interactions, especially since the implicit behavior can't work consistently between nullable and non-nullable return types. The name `returnNullOnMissingStub` is intended to make it more clear what the behavior is so that folks who are opted in to null safety understand why a non-nullable return type and a missing stub aren't compatible.

From the standpoint of avoiding magic in your tests I'd personally recommend you avoid `returnNullOnMissingStub: true` and explicitly stub all the behavior that gets used in your test. If you goal is to retain as much backward compatibility with the pre-migration `mockito` it is fine to use.

> I will wait the new update to solve this.

@srawlins can correct me if I'm wrong, but I don't think we have any changes planned here. This is working as intended.

If you are using `GenerateMocks` you should either stub all behavior, or pass the `returnNullOnMissingStub` argument.

**Comment by mateusdeap** [comment] 2021-04-07 01:34
@natebosch Thanks! So, by what I'm understanding, it would be best practice to actually return something for my methods, is that right?

**Comment by srawlins** [comment] 2021-04-07 02:36
Actually, for #305, I did [land changes](https://github.com/dart-lang/mockito/commit/cee9efd508b587113868d38a296f37702e3c45a3) to allow calling functions which return `void` or `Future<void>`, even if they have not been stubbed. The rationale is that stubbing is all about setting a return value, but regardless of the arguments passed to a `void` method, the "result" is... always void.

These shipped in 5.0.0-nullsafety.6. @mateusdeap can you show what version you are running?

**Comment by srawlins** [comment] 2021-04-07 02:43
@mateusdeap I can reproduce this in a test; this bug slipped through the new tests that landed with that change.

**Comment by mateusdeap** [comment] 2021-04-07 10:42
@srawlins Awesome then! I know you reproduced it at HEAD, but just for the information, I'm using 5.0.3

**Comment by flocbit** [comment] 2021-04-11 07:27
@srawlins Is there an ETA for your fix? Experiencing the same thing as @mateusdeap...

**Comment by srawlins** [comment] 2021-04-11 20:07
This fix has landed on HEAD. I'm waiting for internal review of one more change + a version bump, to be synced to GitHub. Likely tomorrow or Tuesday.

**Closed** 2021-04-12 19:04 UTC

**Comment by milanobrenovic** [comment] 2021-10-15 22:54
> @milanobrenovic can you please provide:
> 
> * the version of mockito you are using
> * a minimal reproduction case
> * the generated mock file you see.
> 
> Since this bug is so old, you are probably hitting a new, different issue, and you should open a new issue.

version of mockito: ^5.0.16 (latest as of now)

my test:

```dart
test("Should perform database batch delete of chat.", () async {
  // Arrange
  const String chatId = "111";
  when(mockDatabase.batch()).thenReturn(mockBatch);

  // Act
  await dataSourceImpl.deleteChat(
    chatId: chatId,
  );

  // Assert
  verifyInOrder([
    mockDatabase.batch(),
    mockBatch.delete(
      "messages",
      where: anyNamed("where"),
      whereArgs: [chatId],
    ),
    mockBatch.delete(
      "chats",
      where: anyNamed("where"),
      whereArgs: [chatId],
    ),
    mockBatch.commit(
      noResult: true,
    ),
  ]);
});
```

deleteChat method:
```dart
@override
Future<void> deleteChat({required String chatId}) async {
  final Batch batch = _database.batch();
  batch.delete(
    "messages",
    where: "chat_id = ?",
    whereArgs: [chatId],
  );
  batch.delete(
    "chats",
    where: "id = ?",
    whereArgs: [chatId],
  );
  await batch.commit( // <--- THE CRASH HAPPENS BECAUSE OF THIS LINE !!!
    noResult: true,
  );
}
```

error:
```
MissingStubError: 'commit'
No stub was found which matches the arguments of this method call:
commit({exclusive: null, noResult: true, continueOnError: null})

Add a stub for this method using Mockito's 'when' API, or generate the mock for MockBatch with 'returnNullOnMissingStub: true'.
```

The error message looks pretty straightforward.

I tried adding those optional nullable parameters "exclusive" and "continueOnError" to be non-nullable, but got the same error.

I also i tried replacing the batch with nullable on stub generation:
```dart
@GenerateMocks([Database], customMocks: [MockSpec<Batch>(returnNullOnMissingStub: true)])
```

But this prints a different error message:
```
type 'Null' is not a subtype of type 'Future<List<Object?>>' in type cast
```

No idea how to fix this for over several weeks. Let me know if i should create a new issue.

**Comment by milanobrenovic** [comment] 2021-10-15 23:06
> @milanobrenovic This is unrelated to #367.
> 
> > MissingStubError: 'commit' 
> > No stub was found which matches the arguments of this method call: 
> > commit({exclusive: null, noResult: true, continueOnError: null})
> 
> > Add a stub for this method using Mockito's 'when' API, or generate the mock for MockBatch with 'returnNullOnMissingStub: true'.
> 
> > The error message looks pretty straightforward.
> 
> When you don't provide a stub, and use `returnNullOnMissingStub: true`, mockito will return null on a missing stub, but the `commit` method must return a non-nullable value.

so how do i fix this crash?

**Comment by srawlins** [comment] 2021-10-15 23:21
Did you try the other suggestion from the error?

> Add a stub for this method using Mockito's 'when' API

**Comment by milanobrenovic** [comment] 2021-10-16 00:02
> No that is stubbing the `batch` method of `mockDatabase`.
> 
> You need to stub the `commit` method of `mockBatch`.

now it worked...

```dart
when(mockBatch.commit(
  noResult: true,
)).thenAnswer((_) async => []);
```

solved the issue. thank you very much.
