### ISSUE TITLE
DiagnosticableMixin.toString' ('String Function({minLevel: DiagnosticLevel}) isnt a valid override of 'Mock.toString' ('String Function()').

### ISSUE THREAD

**Issue by SenadK95** [dart-lang/mockito#233] opened 2020-01-06 14:16 UTC
'Hello i keep getting the following error while using mockito :

DiagnosticableMixin.toString' ('String Function({minLevel: DiagnosticLevel}) isnt a valid override of 'Mock.toString' ('String Function()').

i already tried : 
abstract class MockWithExpandedToString extends Mock {
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug });
}
but this didn't work for me. 

import 'package:mockito/mockito.dart';
class TestData extends MockWithExpandedToString implements BookingFormState {}

anyone knows how to fix this ?

**Comment by srawlins** [comment] 2020-01-07 10:01
You  mention  that this looks  similar to  https://github.com/dart-lang/mockito/issues/228, but your  two code snippets do not reference each other:

```dart
abstract class MockWithExpandedToString extends Mock {
String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug });
}
```

and

```dart
import 'package:mockito/mockito.dart';
class TestData extends Mock implements BookingFormState {}
```

Should TestData extend MockWithExpandedToString instead of Mock?

**Comment by SenadK95** [comment] 2020-01-07 10:08
Yes you're right, i update my first comment. I tried it with MockWithExpandedToString but no succes. You have any idea what else it can be @srawlins ?

**Comment by srawlins** [comment] 2020-01-07 16:55
We need a complete, reproducing example. I don't see where BookingFormState is. I don't see how `DiagnosticLevel` is imported.

I don't think "DiagnosticableMixin.toString' ('String Function({minLevel: DiagnosticLevel}) isnt a valid override of 'Mock.toString' ('String Function()')." would show up if `TestData` extends `MockWithExpandedToString` instead of `Mock`. The message doesn't spell "isn't" correctly which is very suspicious.

**Comment by SenadK95** [comment] 2020-01-08 09:46
@srawlins The reason why "isn't" was misspelled was because of me. I didn't copy the error but typed it over. For my code i made a repository : https://github.com/SenadK95/vitalforest .

**Comment by srawlins** [comment] 2020-01-09 18:53
Thanks for uploading a code repo. It does not reference Mockito though.

**Comment by leecommamichael** [comment] 2020-04-01 06:38
This is really easy to reproduce if you attempt to mock a widget that inherits from InheritedWidget.

**Comment by natebosch** [comment] 2020-04-01 23:08
Adding the manual override of `toString()` to fit the signature does work. Here is the minimal example:

This has static errors:

```dart
import 'package:mockito/mockito.dart';

class Foo {
  @override
  String toString({String extra}) => extra ?? 'default';
}

class MockFoo extends Mock implements Foo {}
```

This fixes the errors:

```dart
import 'package:mockito/mockito.dart';

class Foo {
  @override
  String toString({String extra}) => extra ?? 'default';
}

class MockFoo extends Mock implements Foo {
  @override
  String toString({String extra}) => super.toString();
}
```

You can either copy/paste this into your mocks:

```dart
  @override
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) => super.toString();
```

Or you can define it once:

```dart
abstract class MockWithDiagnosticToString extends Mock {
  @override
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) => super.toString();
}
```

Then replace `extends Mock` with `extends MockWithDiagnosticToString` any place that needs it. Note that in the first 2 comments the definition of `toString` was abstract - it did not provide a body. Replace the `;` with `=> super.toString();` to fix this.

Closing since this can be worked around locally and there are no actions to take in this package.

**Closed by natebosch** 2020-04-01 23:08 UTC
Labels: State: needs info

**Comment by matejthetree** [comment] 2021-04-29 12:28
Can we somehow implement this in code generation?
