### ISSUE TITLE
Cannot mock class with parameter WebSocket - error: The library 'dart:_http' is internal and can't be imported. 

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/mockito#407] opened 2021-05-10 12:19 UTC
Thanks for the wonderful lib!

Sample code:

```
import 'dart:io';
abstract class C {
  void onConnect(WebSocket client);
}
```

Then try to generate mock for class C will yield:

```
import 'dart:_http' as _i3;
import 'package:mockito/mockito.dart' as _i1;
...
class MockC extends _i1.Mock implements _i2.C {
  @override
  void onConnect(_i3.WebSocket? client) =>
      super.noSuchMethod(Invocation.method(#onConnect, [client]),
          returnValueForMissingStub: null);
}
```

Thus I cannot use this wonderful library :(

Screenshot:

![image](https://user-images.githubusercontent.com/5236035/117660871-41315c80-b1d0-11eb-87b8-9c8295bf010d.png)

![image](https://user-images.githubusercontent.com/5236035/117660892-47273d80-b1d0-11eb-8c3f-8237a5a87198.png)

**Comment by srawlins** [comment] 2021-05-10 14:28
Thanks for the report. This is a duplicate of https://github.com/dart-lang/mockito/issues/405. I hope to fix it this week.

**Closed by srawlins** 2021-05-10 14:28 UTC

**Comment by fzyzcjy** [comment] 2021-05-11 00:08
@srawlins Looking forward to the fix! Currently it makes me unable to build my code :(

**Comment by fzyzcjy** [comment] 2021-06-25 14:22
@srawlins Hi I am having error when using the new release:

pubspec

```
dev_dependencies:
  build_runner: ^2.0.0
  mockito: ^5.0.10
```

log:

```
flutter pub run build_runner watch --delete-conflicting-outputs
Failed to precompile build_runner:build_runner:
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_target.g.dart:66:56: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.blackListPatterns.replace(serializers.deserialize(value,
                                                       ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_target.g.dart:72:53: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.outputLocation.replace(serializers.deserialize(value,
                                                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_target.g.dart:77:51: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.buildFilters.replace(serializers.deserialize(value,
                                                  ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_status.g.dart:171:46: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.results.replace(serializers.deserialize(value,
                                             ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_target.g.dart:22:21: Error: The return type of the method '_$DefaultBuildTargetSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_target.g.dart:101:21: Error: The return type of the method '_$OutputLocationSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, OutputLocation object,
                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_request.g.dart:19:21: Error: The return type of the method '_$BuildRequestSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildRequest object,
                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_status.g.dart:64:21: Error: The return type of the method '_$DefaultBuildResultSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/build_daemon-3.0.0/lib/data/build_status.g.dart:146:21: Error: The return type of the method '_$BuildResultsSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildResults object,
                    ^
../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
pub finished with exit code 1
```

**Comment by natebosch** [comment] 2021-06-25 16:31
@fzyzcjy - it looks like you are on an old version of `built_value` that has bugs. Please `flutter pub upgrade` and ensure you get the latest `built_value`.

**Comment by fzyzcjy** [comment] 2021-06-26 00:10
@natebosch Excellent!  `flutter pub upgrade built_value`  then ok
