### ISSUE TITLE
Test fails due to generated mocks uses Stream<List<dynamic>> instead of Stream<List<UserData>>

### ISSUE THREAD

**Issue by Maledikt** [dart-lang/mockito#515] opened 2022-02-10 15:22 UTC
I'm trying to mock a class including a method `watchAllUsers()` which normally returns a `Stream<List<UserData>>`.

Mocking the class with `@GenerateMocks` generates a return type of `Stream<List<dynamic>>` instead.

Using: mockito: ^5.0.17

This might be related to #380

user_list_test.mocks.dart (part):
```
class MockUserBloc extends _i1.Mock implements _i3.UserBloc {
  MockUserBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<dynamic>> get watchAllUsers => (super.noSuchMethod(
      Invocation.getter(#watchAllUsers),
      returnValue: Stream<List<dynamic>>.empty()) as _i4.Stream<List<dynamic>>);

....
```

Test results:
```
test/widget_test/user_list_test.mocks.dart:34:33: Error: The return type of the method 'MockUserBloc.watchAllUsers' is 'Stream<List<dynamic>>', which does not match the return type, 'Stream<List<UserData>>', of the overridden method, 'UserBloc.watchAllUsers'.
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'UserData' is from 'package:vivid_bt_demo_app/repo/local/local_database.dart' ('lib/repo/local/local_database.dart').
Change to a subtype of 'Stream<List<UserData>>'.
  _i4.Stream<List<dynamic>> get watchAllUsers => (super.noSuchMethod(
                                ^
lib/bloc/user/user_bloc.dart:20:30: Context: This is the overridden method ('watchAllUsers').
  Stream<List<UserData>> get watchAllUsers => _localDatabase.usersDao.watchAllUsers();
                             ^
```

**Comment by srawlins** [comment] 2022-02-11 02:36
Is the UserData class by any chance generated?

**Comment by Maledikt** [comment] 2022-02-11 07:50
For the UserData class I planned to use original one, or has this one to be mocked as well?

Changing the generated function `watchAllUsers()` in user_list_test.mocks.dart by replacing `dynamic `with `UserData` let the test pass...

**Comment by srawlins** [comment] 2022-02-11 08:13
The UserData class does not need to be mocked. I am wondering if it is a generated class or a hand-written class.

**Comment by Maledikt** [comment] 2022-02-11 14:15
It's a generated class, based on a Drift (former known as Moor [https://pub.dev/packages/drift](https://pub.dev/packages/drift )) Table.

Table "definition":
```
import 'package:drift/drift.dart';

class User extends Table {
  TextColumn get id => text().withLength(max: 128)();
  TextColumn get firstName => text()();
  TextColumn get lastName => text()();
  BlobColumn get image => blob().nullable()();
  DateTimeColumn get dayOfBirth => dateTime()();

  @override
  Set<Column>? get primaryKey => {id};
}
```
Generated Code:
```
class UserData extends DataClass implements Insertable<UserData> {
  final String id;
  final String firstName;
  final String lastName;
  final Uint8List? image;
  final DateTime dayOfBirth;
  UserData(
      {required this.id,
      required this.firstName,
      required this.lastName,
      this.image,
      required this.dayOfBirth});
  factory UserData.fromData(Map<String, dynamic> data, {String? prefix}) {
    final effectivePrefix = prefix ?? '';
    return UserData(
      id: const StringType()
          .mapFromDatabaseResponse(data['${effectivePrefix}id'])!,
      firstName: const StringType()
          .mapFromDatabaseResponse(data['${effectivePrefix}first_name'])!,
      lastName: const StringType()
          .mapFromDatabaseResponse(data['${effectivePrefix}last_name'])!,
      image: const BlobType()
          .mapFromDatabaseResponse(data['${effectivePrefix}image']),
      dayOfBirth: const DateTimeType()
          .mapFromDatabaseResponse(data['${effectivePrefix}day_of_birth'])!,
    );
  }
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['first_name'] = Variable<String>(firstName);
    map['last_name'] = Variable<String>(lastName);
    if (!nullToAbsent || image != null) {
      map['image'] = Variable<Uint8List?>(image);
    }
    map['day_of_birth'] = Variable<DateTime>(dayOfBirth);
    return map;
  }

  UserCompanion toCompanion(bool nullToAbsent) {
    return UserCompanion(
      id: Value(id),
      firstName: Value(firstName),
      lastName: Value(lastName),
      image:
          image == null && nullToAbsent ? const Value.absent() : Value(image),
      dayOfBirth: Value(dayOfBirth),
    );
  }

  factory UserData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return UserData(
      id: serializer.fromJson<String>(json['id']),
      firstName: serializer.fromJson<String>(json['firstName']),
      lastName: serializer.fromJson<String>(json['lastName']),
      image: serializer.fromJson<Uint8List?>(json['image']),
      dayOfBirth: serializer.fromJson<DateTime>(json['dayOfBirth']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'firstName': serializer.toJson<String>(firstName),
      'lastName': serializer.toJson<String>(lastName),
      'image': serializer.toJson<Uint8List?>(image),
      'dayOfBirth': serializer.toJson<DateTime>(dayOfBirth),
    };
  }

  UserData copyWith(
          {String? id,
          String? firstName,
          String? lastName,
          Uint8List? image,
          DateTime? dayOfBirth}) =>
      UserData(
        id: id ?? this.id,
        firstName: firstName ?? this.firstName,
        lastName: lastName ?? this.lastName,
        image: image ?? this.image,
        dayOfBirth: dayOfBirth ?? this.dayOfBirth,
      );
  @override
  String toString() {
    return (StringBuffer('UserData(')
          ..write('id: $id, ')
          ..write('firstName: $firstName, ')
          ..write('lastName: $lastName, ')
          ..write('image: $image, ')
          ..write('dayOfBirth: $dayOfBirth')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, firstName, lastName, image, dayOfBirth);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is UserData &&
          other.id == this.id &&
          other.firstName == this.firstName &&
          other.lastName == this.lastName &&
          other.image == this.image &&
          other.dayOfBirth == this.dayOfBirth);
}

```

**Comment by srawlins** [comment] 2022-02-11 16:08
Ah then this is a duplicate of https://github.com/dart-lang/mockito/issues/345. The code generators need to be run in a certain order (I suppose Mockito should just go last). I don't have documentation written up for this yet, but see https://github.com/dart-lang/mockito/issues/345#issuecomment-794411760.

**Closed by srawlins** 2022-02-11 16:08 UTC
