### ISSUE TITLE
.captured sometimes returns strange closures

### ISSUE THREAD

**Issue by enyo** [dart-lang/mockito#45] opened 2016-11-29 17:05 UTC
I have this calls:

```dart
VerificationResult result = verify(transaction.queueMutations(inserts: captureThat(isList)));
print(result.callCount);
print(result.captured.length);
result.captured.forEach(print);
```

and the output is:

```
6
9
Closure: (Transaction) => dynamic
Closure: (Transaction) => dynamic
Closure: (Transaction) => dynamic
[Transaction.69140b7c-742f-469f-b039-303af8390c67]
[Instance of 'User']
[Transaction.69140b7c-742f-469f-b039-303af8390c67]
[Instance of 'User']
[Transaction.69140b7c-742f-469f-b039-303af8390c67]
[Instance of 'User']
```

First of all: it seems very strange that captured calls for `captureThat(isList)` would return closures.
Then it seems strange that the `.callCount` differs from `.captured.length`.
And lastly: where do those Closures come from?

I haven't found any better way to debug this, but maybe you could guide me in the right direction to get to the bottom of this.

Thanks

**EDIT**: For the record: the last 6 entities in the `result.captured` list are the expected values.

**Comment by srawlins** [comment] 2018-06-16 02:53
Looks like these were caused by captured arguments being left around from previous interactions or a previous test. I'll close this for now as such. But please re-open if you find this to happen even with fresh mock objects.

**Closed by srawlins** 2018-06-16 02:53 UTC
